#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Feb 17 19:50:46 2018

@author: dcui19
"""

"below: skimage package imports"
import os
from skimage import io
from skimage.color import rgb2gray
from skimage import data
from skimage.viewer import ImageViewer
from skimage import data, exposure, img_as_float
from skimage.viewer.plugins.lineprofile import LineProfile
import cv2
import numpy as np
from matplotlib import pyplot as plt

"able to separate the color channels of a RGB image"
rgb_image = io.imread('MoTe2 S4D.jpg')
image_red = rgb_image[:,:,0]
image_green = rgb_image[:,:,1]
image_blue = rgb_image[:,:,2]
image_gray = rgb2gray(rgb_image)


"histogram for showing color contrast values: work in progress"
color = ('b','g','r')
for i,col in enumerate(color):
    histr = cv2.calcHist([rgb_image],[i],None,[256],[0,256])
    plt.plot(histr,color = col)
    plt.xlim([0,256])
plt.show()

"two sections below: for viewing the new images with separated color channels"
viewer = ImageViewer(image_red)
viewer2 = ImageViewer(image_green)
viewer3 = ImageViewer(image_blue)
viewer4 = ImageViewer(image_gray)

viewer.show()
viewer2.show()
viewer3.show()
viewer4.show()
